Scalars, Vectors, Matrices, and Tensors

- Scalars:
- Vectors:
- Matrices:
- Tensors:

In [1]:
# Transpose of  matrix
import numpy as np
A = np.array([[1, 2], [3, 4]])
A_transpose = A.T
print("Original Matrix:\n", A)
print("Transposed Matrix:\n", A_transpose)

Original Matrix:
 [[1 2]
 [3 4]]
Transposed Matrix:
 [[1 3]
 [2 4]]


In [9]:
# Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
A @ B, B @ A

(array([[19, 22],
        [43, 50]]),
 array([[23, 34],
        [31, 46]]))

In [10]:
np.dot(A, B), np.dot(B, A)

(array([[19, 22],
        [43, 50]]),
 array([[23, 34],
        [31, 46]]))

In [12]:
# Inverse of a Matrix
A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)
print("Original Matrix:\n", A)
print("Inverse Matrix:\n", A_inv)

Original Matrix:
 [[1 2]
 [3 4]]
Inverse Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [17]:
# Determinant of a Matrix
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [15]:
A_inv @ A, A @ A_inv

(array([[1.00000000e+00, 0.00000000e+00],
        [1.11022302e-16, 1.00000000e+00]]),
 array([[1.0000000e+00, 0.0000000e+00],
        [8.8817842e-16, 1.0000000e+00]]))

In [31]:
# 1-Norm of a Matrix
# How it works is that it computes the maximum absolute column sum of the matrix. In other words, it sums the absolute values of each column and then takes the maximum of those sums.
A = np.array([[1, -7],[-2,-3]])
np.linalg.norm(A, 1)

np.float64(10.0)

In [32]:
# Infinty Norm of a Matrix
# How it works is that it computes the maximum absolute row sum of the matrix. In other words, it sums the absolute values of each row and then takes the maximum of those sums.
np.linalg.norm(A, np.inf)

np.float64(8.0)

In [33]:
# Euclidean Norm of a Matrix
# How it works is that it flattens the matrix into a vector and then computes the Euclidean norm of that vector.
np.linalg.norm(A, 'fro')

np.float64(7.937253933193772)

In [36]:
# Trace of a Matrix
# The trace of a matrix is the sum of the elements on the main diagonal (from the top left to the bottom right) of a square matrix. It is denoted as tr(A)
print(f'Original Matrix:\n{A}')
trace_A = np.trace(A)
print(f'Trace of the Matrix: {trace_A}')

Original Matrix:
[[ 1 -7]
 [-2 -3]]
Trace of the Matrix: -2


Types of Matrices
- Diagonal Matrix: A matrix where all the elements outside the main diagonal are zero.
- Identity Matrix: A square matrix with ones on the main diagonal and zeros elsewhere.
- Symmetric Matrix: A matrix that is equal to its transpose, meaning A = A^T.
- Orthogonal Matrix: A square matrix whose rows and columns are orthogonal unit vectors (orth
- onormal vectors). An orthogonal matrix Q satisfies the condition Q^T Q = I, where I is the identity matrix.
- Singular Matrix: A square matrix that does not have an inverse. This occurs when the determinant of the matrix is zero.
- Sparse Matrix: A matrix in which most of the elements are zero. Sparse matrices are often used in scientific computing and data analysis to save memory and computational resources.
- Upper Triangular Matrix: A square matrix where all the elements below the main diagonal are zero.
- Lower Triangular Matrix: A square matrix where all the elements above the main diagonal are zero
- Hermitian Matrix: A complex square matrix that is equal to its conjugate transpose, meaning A = A^*. Hermitian matrices have real eigenvalues and orthogonal eigenvectors.
- Skew-Symmetric Matrix: A square matrix that is equal to the negative of its transpose, meaning A = -A^T. Skew-symmetric matrices have purely imaginary eigenvalues or zero eigenvalues.

Read more about these types of matrices from online sources such as [Wikipedia](https://en.wikipedia.org/wiki/Matrix_(mathematics)) or [Khan Academy](https://www.khanacademy.org/math/linear-algebra/matrix-transformations#types-of-matrices).

# Eigendecomposition of a Matrix
Eigendecomposition is a fundamental concept in linear algebra that allows us to express a matrix in terms of its eigenvalues and eigenvectors. For a square matrix A, if there exists a non-zero vector v and a scalar λ such that Av = λv, then v is called an eigenvector of A, and λ is the corresponding eigenvalue. The eigendecomposition of a matrix A can be expressed as A = PDP^(-1), where P is the matrix of eigenvectors, D is the diagonal matrix of eigenvalues, and P^(-1) is the inverse of the matrix of eigenvectors. This decomposition is particularly useful in various applications, including solving systems of linear equations, performing dimensionality reduction, and analyzing the stability of systems. To compute the eigendecomposition of a matrix in Python, you can use the `numpy.linalg.eig` function, which returns the eigenvalues and the corresponding eigenvectors of a square matrix. For example:
```python
import numpy as np
A = np.array([[4, -2], [1, 1]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)
```
In this example, the `numpy.linalg.eig` function computes the eigenvalues and eigenvectors of the matrix A. The eigenvalues are returned as a 1D array, while the eigenvectors are returned as a 2D array, where each column corresponds to an eigenvector. The eigendecomposition of the matrix A can be used to analyze its properties and perform various operations, such as diagonalization, which can simplify computations and provide insights into the behavior of the system represented by the matrix.

In [38]:
# Av = λv
A = np.array([[4, 1], [2, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [5. 2.]
Eigenvectors:
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


# Singular Value Decomposition (SVD)

# Principal Component Analysis (PCA)